
name: 
services:
  react-app:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./.env
    ports:
      - "3009:5173"
    volumes:
      - ./src:/usr/src/app/src

images: backendMicro-compose:1.0