version: '3.8'

services:
  react-app:
    #stdin_open: true
    #tty: true
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - REACT_NAME=JUANES
    env_file:
      - ./.env
    ports:
      - "8080:80"
  